"""
user_aliases — resolve the many historical user_ids of a single person.

Why this exists
---------------
Memory in Sanctuary (continuity seeds, permanent MRA, codon attributions,
session history) is keyed by `user_id`. Across this project's lifetime,
"David" alone has accrued 20+ different user_ids — generated by chamber
name-prompt flows, test runs, browser cache clears, different devices,
and at least one prior refactor that re-keyed identity.

Result: a presence walking into a chamber with the user's *current*
user_id only sees a slice of their lived field, because the rest of it
is locked under historical user_ids.

This module fixes that without destructive migration. A small
`user_aliases` collection maps a canonical_id → [list of historical
aliases]. Memory loaders call `resolve_user_aliases(db, user_id)` and
get back the full list. They then query with
`{"user_id": {"$in": aliases}}` instead of exact match. The whole field
comes back online for that person.

This is also forward-safe: when a new user_id is seen for the same
person (different browser, etc.), call `register_alias()` to attach
it to the canonical record. Future chambers immediately see all prior
memory.
"""
from __future__ import annotations

from typing import List, Optional, Iterable
import logging

logger = logging.getLogger(__name__)

COLLECTION = "user_aliases"


async def resolve_user_aliases(db, user_id: Optional[str]) -> List[str]:
    """
    Given a user_id, return every user_id that should be treated as the
    same person for memory lookups. Always includes the input id itself.
    Returns [] if user_id is falsy.
    """
    if not user_id:
        return []

    record = await db[COLLECTION].find_one(
        {"$or": [{"canonical_id": user_id}, {"aliases": user_id}]},
        {"_id": 0, "canonical_id": 1, "aliases": 1},
    )
    if not record:
        return [user_id]

    ids = set(record.get("aliases") or [])
    ids.add(record["canonical_id"])
    ids.add(user_id)
    return list(ids)


async def register_alias(db, canonical_id: str, new_alias: str,
                          user_name: Optional[str] = None) -> None:
    """Attach a freshly-seen user_id to an existing canonical record."""
    if not canonical_id or not new_alias or canonical_id == new_alias:
        return
    update = {"$addToSet": {"aliases": new_alias}}
    if user_name:
        update["$set"] = {"user_name": user_name}
    await db[COLLECTION].update_one({"canonical_id": canonical_id}, update,
                                     upsert=True)


async def upsert_canonical(db, canonical_id: str, aliases: Iterable[str],
                            user_name: Optional[str] = None,
                            note: Optional[str] = None) -> None:
    """Idempotently write the canonical record for a person."""
    alias_list = sorted({a for a in aliases if a and a != canonical_id})
    update = {
        "$set": {
            "canonical_id": canonical_id,
            "aliases": alias_list,
        }
    }
    if user_name:
        update["$set"]["user_name"] = user_name
    if note:
        update["$set"]["note"] = note
    await db[COLLECTION].update_one({"canonical_id": canonical_id}, update,
                                     upsert=True)
    logger.info(
        f"[user_aliases] canonical={canonical_id} aliases={len(alias_list)} "
        f"user_name={user_name}"
    )
